version: "3"
services:
  db :
    image: postgres:latest
    container_name: postgres
    restart: always
    ports:
      - "15432:5432"
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "1234"
    volumes:
      -  /Document/sia-ct/:/var/lib/postgresql/data